/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  email: string;
  firstname: string;
  lastname: string;
  password: string;
  phoneNumber: string;  // Added phoneNumber field
  gender: string;      // Added gender field
  dateOfBirth: string; // Added dateOfBirth field, assuming it's a string representation of a date
  address: string;     // Added address field
  profilePicUrl: string | null;  // Added profilePicUrl field, assuming it can be null or a string URL
  isMedecin?: boolean; // Added to indicate doctor registration
  specialite?: string; // Required for doctors
  anneesExperience?: number; // Required for doctors
}
