/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { Role } from '../models/role';

export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  gender?: string;
  id?: number;
  lastModifiedDate?: string;
  lastname?: string;
  name?: string;
  password?: string;
  phoneNumber?: string;
  profilePicUrl?: string;
  roles?: Array<Role>;
  username?: string;
  pendingUnbanRequest?: boolean; // Ajoutez cette propriété
  // Ajout de l'adresse
  address?: string;  // Add address field
  isOAuthUser?: boolean; // Ajoutez cette propriété pour indiquer si l'utilisateur est un utilisateur OAuth
  specialite?: string; // Added for doctors
  anneesExperience?: number; // Added for doctors
  adresse?: string; // pour compatibilité

}
